version: '3.8'

services:
  gomasters_app:
    build: ./
    command: ./main
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
    - message="hi there"
    - DB_PASSWORD="admin"
  db:
    restart: always
    image: postgres:latest
#    volumes:
#      - - ./.db/pg/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="admin"
    ports:
      - 5432:5436
